/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as RfServicesRouteImport } from './routes/Rf-Services'
import { Route as ProjectManagementRouteImport } from './routes/ProjectManagement'
import { Route as ConstructionServicesRouteImport } from './routes/ConstructionServices'
import { Route as IndexRouteImport } from './routes/index'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const RfServicesRoute = RfServicesRouteImport.update({
  id: '/Rf-Services',
  path: '/Rf-Services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectManagementRoute = ProjectManagementRouteImport.update({
  id: '/ProjectManagement',
  path: '/ProjectManagement',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructionServicesRoute = ConstructionServicesRouteImport.update({
  id: '/ConstructionServices',
  path: '/ConstructionServices',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ConstructionServices': typeof ConstructionServicesRoute
  '/ProjectManagement': typeof ProjectManagementRoute
  '/Rf-Services': typeof RfServicesRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ConstructionServices': typeof ConstructionServicesRoute
  '/ProjectManagement': typeof ProjectManagementRoute
  '/Rf-Services': typeof RfServicesRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ConstructionServices': typeof ConstructionServicesRoute
  '/ProjectManagement': typeof ProjectManagementRoute
  '/Rf-Services': typeof RfServicesRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ConstructionServices'
    | '/ProjectManagement'
    | '/Rf-Services'
    | '/about'
    | '/careers'
    | '/contact'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ConstructionServices'
    | '/ProjectManagement'
    | '/Rf-Services'
    | '/about'
    | '/careers'
    | '/contact'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/ConstructionServices'
    | '/ProjectManagement'
    | '/Rf-Services'
    | '/about'
    | '/careers'
    | '/contact'
    | '/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConstructionServicesRoute: typeof ConstructionServicesRoute
  ProjectManagementRoute: typeof ProjectManagementRoute
  RfServicesRoute: typeof RfServicesRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Rf-Services': {
      id: '/Rf-Services'
      path: '/Rf-Services'
      fullPath: '/Rf-Services'
      preLoaderRoute: typeof RfServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ProjectManagement': {
      id: '/ProjectManagement'
      path: '/ProjectManagement'
      fullPath: '/ProjectManagement'
      preLoaderRoute: typeof ProjectManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ConstructionServices': {
      id: '/ConstructionServices'
      path: '/ConstructionServices'
      fullPath: '/ConstructionServices'
      preLoaderRoute: typeof ConstructionServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConstructionServicesRoute: ConstructionServicesRoute,
  ProjectManagementRoute: ProjectManagementRoute,
  RfServicesRoute: RfServicesRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
